# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"

services:

  fast_api:

    image: andrsolo21/fast_code

    command: uvicorn main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    depends_on:
      - grpc_server


  grpc_server:

    image: andrsolo21/grpc_server_code

    command: python server_grpc.py

    ports:
      - "50051:50051"

    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "ml_models"
      POSTGRES_USER: "ml_user"
      POSTGRES_PASSWORD: "difficult_password"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

