# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\x13\x41vailableModelTypes\x12\x1d\n\x15\x61vailable_model_types\x18\x01 \x03(\t\"&\n\x0cMLModelsList\x12\x16\n\x0eml_models_list\x18\x01 \x03(\t\"\x98\x02\n\x12\x43reateModelRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\r\n\x05\x61lpha\x18\x02 \x01(\x02\x12\x15\n\rfit_intercept\x18\x03 \x01(\x08\x12\x11\n\tnormalize\x18\x04 \x01(\x08\x12\x10\n\x08max_iter\x18\x05 \x01(\x05\x12\x14\n\x0crandom_state\x18\x06 \x01(\x05\x12\x10\n\x08splitter\x18\x07 \x01(\t\x12\x11\n\tmax_depth\x18\x08 \x01(\x05\x12\x19\n\x11min_samples_split\x18\t \x01(\x05\x12\x18\n\x10min_samples_leaf\x18\n \x01(\x05\x12 \n\x18min_weight_fraction_leaf\x18\x0b \x01(\x02\x12\x11\n\tcriterion\x18\x0c \x01(\t\"8\n\x14ResponseCreatedModel\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t2\xfc\x01\n\x07Greeter\x12U\n\x16GetAvailableModelTypes\x12\x18.helloworld.HelloRequest\x1a\x1f.helloworld.AvailableModelTypes\"\x00\x12G\n\x0fGetMLModelsList\x12\x18.helloworld.HelloRequest\x1a\x18.helloworld.MLModelsList\"\x00\x12Q\n\x0b\x43reateModel\x12\x1e.helloworld.CreateModelRequest\x1a .helloworld.ResponseCreatedModel\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _HELLOREQUEST._serialized_start=30
  _HELLOREQUEST._serialized_end=58
  _AVAILABLEMODELTYPES._serialized_start=60
  _AVAILABLEMODELTYPES._serialized_end=112
  _MLMODELSLIST._serialized_start=114
  _MLMODELSLIST._serialized_end=152
  _CREATEMODELREQUEST._serialized_start=155
  _CREATEMODELREQUEST._serialized_end=435
  _RESPONSECREATEDMODEL._serialized_start=437
  _RESPONSECREATEDMODEL._serialized_end=493
  _GREETER._serialized_start=496
  _GREETER._serialized_end=748
# @@protoc_insertion_point(module_scope)
